/* eslint-disable @next/next/google-font-preconnect */
/* eslint-disable @next/next/no-title-in-document-head */
import { Head, Html, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <title>Portfolio Eben</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://img.pixers.pics/pho_wat(s3:700/FO/57/40/61/13/700_FO57406113_0e794e935aab8ecafb2c01d0280914c5.jpg,700,700,cms:2018/10/5bd1b6b8d04b8_220x50-watermark.png,over,480,650,jpg)/posters-feu-alphabet-lettre-e.jpg.jpg"
        />
        <link href="https://fonts.googleapis.com" />
        <link href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
